name: ci
env:
  PNPM_VERSION: "10.28.1"
  NODE_VERSION: "24.11.0"

on:
  push:
  branches: [main]

jobs:
  ci:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: run check
        run: pnpm check
